---
name: Class-Define
version: 0.0401
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: define class easily and anywhere
license: perl
resources:
  license: ~
build_requires:
  Test::More: 0
provides:
  Class::Define:
    file: lib/Class/Define.pm
    version: 0.0401
  Class::Define::AnonymousClass:
    file: lib/Class/Define.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
